name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
       submodules: true
    - name: Initialize Xcode Project
      run: swift package generate-xcodeproj
    - name: Build
      run: swift build -v -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"
# Removed, until there is a fix to xcodebuild failing to correctly build packages with resources.
#     - name: Run tests
#       run: xcodebuild test -destination 'name=iPhone 11' -scheme 'Incito-Package'
